### ISSUE TITLE
Example of daily coding problems and progress

### ISSUE THREAD

**Issue by Today-To-Do** [Today-To-Do/coding-workbook#1]
# Tasks

- [ ] [226. Invert Binary Tree](https://leetcode.com/problems/invert-binary-tree/)

- [x] [954. Array of Doubled Pairs](https://leetcode.com/problems/array-of-doubled-pairs/)
  + 这道题思路很简单啦。。。巴拉巴拉

<details>
 <summary>【cpp】Solution of 954</summary>

```cpp
class Solution {
public:
    bool canReorderDoubled(vector<int>& A) {
        sort(A.begin(), A.end());
        unordered_map<int, int> hash;
        for(int i = 0; i < A.size(); i++) {
            hash[A[i]] += 1;
        }
        int k = 0;
        for(k = 0; k < A.size(); k++) {
            if(A[k]>=0) break;
        }
        int cnt = 0;
        for(int i = k; i < A.size(); i++) {
            if(A[i] > 0 && hash[A[i]]) {
                if(hash[2*A[i]]) {
                    cnt += 1;
                    hash[A[i]] -= 1;
                    hash[2*A[i]] -= 1;
                }
                else return false;
            } else {
                if(hash[A[i]] % 2 == 0) {
                    cnt += hash[A[i]] / 2;
                    hash[A[i]] = 0;
                } else return false;
            }
        }
        for(int i = k-1; i>=0; i--) {
            if(hash[A[i]]) {
                if(hash[2*A[i]]) {
                    cnt += 1;
                    hash[A[i]] -= 1;
                    hash[2*A[i]] -= 1;
                }
                else return false;
            }
        }
        return true;
        
    }
};


```
</details>

**Comment by Today-To-Do** [comment]
To create a folded code block, edit the #title and fill your code in by the following format:
 
````html
<details>
 <summary>#title</summary>

```cpp
# fill your code here
```
</details>
````

**Comment by Today-To-Do** [comment]
To Create your own TODO, use the following markdown syntax:
```
- [ ] [226. Invert Binary Tree](https://leetcode.com/problems/invert-binary-tree/)

- [ ] [954. Array of Doubled Pairs](https://leetcode.com/problems/array-of-doubled-pairs/)
```
